MyChat/Models/ErrorViewModel.cs
using System;

namespace MyChat.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyChat/ViewModels/Account/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MyChat.ViewModels.Account
{
    public class LoginViewModel
    {
        public string Username { get; set; }

        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

MyChat/Controllers/AccountController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyChat.Classes;
using MyChat.DTO;
using MyChat.ViewModels.Account;

namespace MyChat.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult SignIn()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignIn(LoginViewModel model)
        {
            var isValidLogin = RestService.User.IsValidLogin(model.Username, model.Password);

            if (isValidLogin)
            {
                var user = RestService.User.GetByUsername(model.Username);
                var token = TokenIssuer.IssueToken(user);

                HttpContext.Session.SetString("JWToken", token);

                return Ok(true);
            }

            return BadRequest();    
        }

        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignUp([FromBody] UserDto userDto)
        {
            var result = RestService.User.AddUser(userDto);

            if (result.IsSucceeded)
            {
                return Ok(true);
            }

            return BadRequest(result.Message);
        }

        public IActionResult SignOut()
        {
            HttpContext.Session.Remove("JWToken");

            return RedirectToAction("Index", "Home");
        }
    }
}

MyChat/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MyChat.Controllers
{
    [Authorize(AuthenticationSchemes = "Bearer")]
    public abstract class BaseController : Controller
    {
    }
}

MyChat/Controllers/ChatRoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MyChat.Controllers
{
    public class ChatRoomController : BaseController
    {
        public IActionResult Room(string name)
        {
            if (!string.IsNullOrWhiteSpace(name))
            {
                ViewBag.RoomName = name;

                return View();
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

MyChat/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyChat.Models;

namespace MyChat.Controllers
{
    public class HomeController : BaseController
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyChat/Controllers/RestController.cs
using MyChat.Classes.Rest;
using Microsoft.AspNetCore.Mvc;
using MyChat.Classes;

namespace MyChat.Controllers
{
    [Route("Rest")]
    public class RestController : Controller
    {
        [HttpGet("Get")]
        public IActionResult Get([FromQuery] string endpoint)
        {
            return Ok(GetRequest.Send($"{SystemVariables.RestAPI}/{endpoint}"));
        }

        [HttpPost("Post")]
        public IActionResult Post([FromQuery] string endpoint, [FromBody] object data)
        {
            return Ok(PostRequest.Send($"{SystemVariables.RestAPI}/{endpoint}", data));
        }
    }
}

MyChat/Views/ChatRoom/Room.cshtml
@{
    ViewData["Title"] = ViewBag.RoomName;
}

@section Scripts{
    <script src="~/lib/aspnet-signalr/signalr.min.js"></script>
    <script src="~/js/fireworks.js"></script>
}



<h4 class="room-title">Room - @ViewBag.RoomName</h4>

<div class="chat-room">
    <div id="chatBox" class="chat-box">
        <div class="wrapper">
            <div id="messageList" class="message-list"></div>
            <div id="userList" class="user-list"></div>
        </div>
    </div>
    <div class="bottom">
        <textarea id="messageBox" placeholder="Message.."></textarea>
        <button id="sendMessageButton" class="btn btm-primary">Send</button>
    </div>
</div>

<canvas id='myCanvas' class="firework-canvas"></canvas>

<script>
    const start = (function () {
        const chatRoom = '@ViewBag.RoomName';
        const connection = new signalR.HubConnectionBuilder().withUrl("/ChatHub").build();
        const messageList = $('#messageList');
        const messageBox = $('#messageBox');
        const userList = $('#userList');

        connection.start()
            .then(setupClient)
            .catch(function (err) {
            return console.error(err.toString());
        });

        function setupClient() {
            connection.invoke('Register', chatRoom);
            connection.on('ReceiveMessage', recieveMessage);
            connection.on('UserJoined', userJoined)
            connection.on('UserLeaved', userLeaved)
            connection.on('ReceiveClientList', receiveClientList)

            getUserList();
            bindEvents();
        }

        function getUserList() {
            connection.invoke('GetClientList');
        }

        function userJoined(name, identifier) {
            getUserList();
        }

        function userLeaved(name, identifier) {
            getUserList();
        }

        function receiveClientList(clients) {
            userList.empty();

            for (let i in clients) {
                userList.append(`
                    <label id="${clients['identifier']}">${clients[i]['name']}</label>`
                );
            }
        }

        function recieveMessage(sender, message) {
            messageList.append(`
                <div class="message">
                    <label>${sender}: </label>
                    <p>${message}</p>
                </div>`
            );

            messageList.animate({
                scrollTop: messageList.prop('scrollHeight')
            }, 500);
        }

        function bindEvents() {
            $("#sendMessageButton").click(sendMessage);
            $('#messageBox').on('keydown', function (event) {
                if (event.keyCode === 13) {
                    sendMessage();
                    event.preventDefault();
                    return false;
                }

                return true;
            });
        }

        function sendMessage() {
            const message = messageBox.val();

            if (message.length > 0) {
                connection.invoke("SendMessage", message).catch(function (err) {
                    return console.error(err.toString());
                });
                
                messageBox.val('');
            }
        }
    });

    $(document).ready(start);
</script>

MyChat/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
    Layout = "~/Views/Shared/_EmptyLayout.cshtml";
}

@section Scripts{ 
    <script src="~/js/login.js"></script>
}

<div class="login-container text-center">
    <img class="logo" src="~/images/logo_transparent1.png" />
    <p>Select which category of chat room you want to enter below.</p>

    <div class="card-container">
        <a class="card" href="@Url.Action("Room", "ChatRoom", new { name = "Work"})">
            <label>Work</label>
        </a>
        <a class="card" href="@Url.Action("Room", "ChatRoom", new { name = "Programming"})">
            <label>Programming</label>
        </a>
        <a class="card" href="@Url.Action("Room", "ChatRoom", new { name = "Math"})">
            <label>Math</label>
        </a>
        <a class="card" href="@Url.Action("Room", "ChatRoom", new { name = "Physics"})">
            <label>Physics</label>
        </a>
    </div>
</div>

MyChat/Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyChat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body class="empty-container">
    <div class="container">
        @RenderBody()
    </div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <script>
        const localUrl = location.protocol + '//' + location.host + '@Url.Content("~/")';
    </script>
</body>
</html>

MyChat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyChat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyChat</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignOut">Sign out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @RenderBody()
    </div>
    <img src="~/images/onlylogo.png" class="watermark-logo">
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <script>
        const localUrl = location.protocol + '//' + location.host + '@Url.Content("~/")';
    </script>
</body>
</html>